### PR TITLE
Add properties for degraded and max response time

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Comment by bitfield** [comment]
Hey @SaaldjorMike! Thanks for the PR. This looks good. What's it about?

**Comment by SaaldjorMike** [comment]
I think Checkly's own documentation describes this feature pretty well: https://checklyhq.com/docs/api-checks/limits/

The idea is that you can define a threshold (degraded response time) for when a service is so slow it will be marked as degraded. Similarly, the max response time defines at which point it will mark it as failed.

**Comment by bitfield** [comment]
Sounds great! Would you mind adding a test that fails without your commit, and passes with it? I'll be happy to merge this.

**Comment by tnolet** [comment]
@bitfield @SaaldjorMike let me know if I can help with getting this PR merged!

**Comment by bitfield** [comment]
@SaaldjorMike how are you getting on? Do you want a hand with writing suitable tests?

**Comment by SaaldjorMike** [comment]
@bitfield @tnolet Sorry for not getting back. I'd love if any of you could help me get this wrapped up and merged in.

**Comment by bitfield** [comment]
No problem, @SaaldjorMike! I'll add the finishing touches to this next week, get your approval, and merge it! Thanks again for the help. 😄

**Comment by mwl** [comment]
Hi @bitfield. @SaaldjorMike and I are struggling a bit to understand what you are asking. With my limited Go knowledge any test that is using the `DegradedResponseTime` and `MaxResponseTime` parameters will fail due to parameter checking in the language.

I believe the integration test in https://github.com/bitfield/checkly/blob/2478836254f3b1a817b72e030c9f504627feb160/checkly_integration_test.go#L32-L33 should be sufficient of what you are asking? If not, could you please elaborate on what you had in mind?

**Comment by bitfield** [comment]
@mwl while the integration tests are fine, I've made basically the same change to the unit tests, so that without Mike's additional struct fields, both unit and integration tests fail the same way. If you check the box on this PR that says 'Allow edits from maintainers', I can push this change to your branch and we'll be good to go.

**Comment by bitfield** [comment]
This is all ready for you @mwl and @SaaldjorMike — as soon as you give me permission to push the branch, let me know and I will do so.

**Comment by SaaldjorMike** [comment]
@bitfield Seems like that button doesn't really show itself. Maybe that is because the fork is part of our organisation rather than a personal repo? Anyhow, I've added you with write access to our fork as I expect to remove this fork as soon as this is merged in anyways.

**Comment by bitfield** [comment]
Cool, thank you! Pushed.

**Comment by bitfield** [comment]
Tagged as `v0.2.1` upstream. Thanks again for the patch, great work!

**Comment by SaaldjorMike** [comment]
Awesome! Appreciate the help!

**Pull request merged**
