### PR TITLE
remove alertChannels from API + configure API with env var

### PR DESCRIPTION
**Pull request by tnolet**
This PR has two changes:

1. It removes the "alertChannels" struct from the Check entity. Setting alert channels using the API is deprecated.

2. It allows you to set the URL of the check API with the CHECKLY_API_URL environment variable. If it is not provided, it falls back to the standard production URL. This makes local testing a lot easier.

### CODE REVIEW

**Comment by bitfield** [comment]
If you can no longer set alert channels with Go/Terraform, how do you do it? Will all checks now have to use the same global alert channels configured in the account?

**Comment by tnolet** [comment]
@bitfield this is now done through alert channel subscriptions. The definition of the alert channels is done outside of the API as we can not deliver a consistent API for this (especially in the future when we add many different types of alerting mechanism with 3rd parties like Pagerduty). This is a fair compromise.

However, we should expose the subscription mechanism in the public API, which is 100% consistent and easy to grasp.

Let me add that and update this PR.

**Comment by tnolet** [comment]
@bitfield I updated the following:

- Checks created using the SDK (or via the API in general) will be subscribed to all alert channels.
- There now is an `/alert-channels` API endpoint to manage this if users would want to turn these on/off for specific checks or channel. 

See: https://checklyhq.com/docs/api/#checkly-api-alert-channels

This endpoint is not part of the SDK yet (just like some other API endpoints)

**Comment by bitfield** [comment]
@tnolet how are you getting on with the API changes? Do you want me to review this PR yet, or is there anything else we need to on the SDK side?

**Comment by tnolet** [comment]
@bitfield I think it is actually better to close this PR. I will keep the branch / code and add some more changes pretty soon. Then we can do one update to the Terraform integration and don't bother users with two updates in a fairly short period.

**Pull request closed without merging**
